### PR TITLE
Added feature: Copy URL to Clipboard

### PR DESCRIPTION
**Pull request by emw3**
Hello,

Added a button into the API Explorer to copy the full URL to the clipboard, this addition could improve the UX when you are exploring the available endpoints.

In the following case, the text `https://pokeapi.co/api/v2/pokemon/ditto` will be copied to the clipboard.

Copy to Clipboard

### CODE REVIEW

**Comment by Naramsim** [comment]
Super cool addition, I'll test it and report back

**Comment by Naramsim** [comment]
@emw3, thanks so much for the contribution. Everything looks good but the `package-lock.json`. Could you please update your node and npm and regenerate it?

**Comment by emw3** [comment]
@Naramsim I've regenerated the `package-lock.json` using the latest node LTS version `16.3.2`. Let me know if anything else is needed.

**Comment by Naramsim** [comment]
I merged the PR in the staging branch

**Pull request merged**
