### PR TITLE
Add pokemon cries field

### PR DESCRIPTION
**Pull request by FallenDeity**
Add cries field to Pokemon model after merge of [pr #1030](https://github.com/PokeAPI/pokeapi/pull/1030).

- Example Response 
```json
"cries": {
     "latest": "https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/35.ogg",
     "legacy": "https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/legacy/35.ogg"
}
```
- Field
```json
{
     "name": "cries",
     "description": "A set of cries used to depict this Pokémon in the game. A visual representation of the various cries can be found at <a href='https://github.com/PokeAPI/cries#cries'>PokeAPI/cries</a>",
     "type": "PokemonCries"
}
```
- Model
```json
{
    "name":"PokemonCries",
    "fields":[
        {
            "name":"latest",
            "description":"The latest depiction of this Pokémon's cry.",
            "type":"string"
        },
        {
            "name":"legacy",
            "description":"The legacy depiction of this Pokémon's cry.",
            "type":"string"
        }
    ]
}
```

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, can you get rid of all the images?

**Comment by FallenDeity** [comment]
Aight, will do.

**Comment by FallenDeity** [comment]
@Naramsim done

**Comment by Naramsim** [comment]
Thanks!

**Pull request merged**
